application:
  http:
    virtualcoin-url: http://127.0.0.1:51200
    rpc-user: vcoindisco
    rpc-password:

discord:
  bot:
    token:

    notification-channel-id: 
    notification-user-id: 
  channel-default-language:
    en:
      list:
      - 
  event:
    admin:
      user:
        ids:
        - 
    text:
    #      channel-command-channel-ids:
    #      - 
    #      - 
    emoji:     
      notification-channel-id: 
      command:
        gratuity:
          emojis:
          - id: 
            value: 1
          - id: 
            value: 10
          - id: 
            value: 100
          - id: 
            value: 1000

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:vcoins.db
