application:
  http:
    virtualcoin-url: http://127.0.0.1:51200
    rpc-user: hoge
    rpc-password: hogehoge123
  debug:
    # VIRTUALCOINのregtestの動作が変なので、localの動作確認はbitcoinで行う
    mining: docker-compose exec -T vcoins-server bitcoin-cli -regtest generate
discord:
  bot:
    token:
  #    notification-channel-id: 
  #    notification-user-id: 
  channel-default-language:
    en:
      list:
      - 
  event:
    admin:
      user:
        ids:
        - 
        - 
    text:
      #      channel-command-channel-ids:
      #      - 
      #      - 
      #      - 
      additional-enable-channel-commands:
      - mining
      - clear-cache
    emoji:
      notification-channel-id: 
      command:
        gratuity:
          emojis:
          - id: 
            value: 1
          - id: 
            value: 10
          - id: 
            value: 100
          - id: 
            value: 1000

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/tmp/db
    username: root
    password: root
