application:
  http:
    virtualcoin-url: http://127.0.0.1:51200
    rpc-user: vcoindisco
    rpc-password:

discord:
  bot:
    token:

    notification-channel-id: 438667563782897674
    notification-user-id: 418273971293650946
  channel-default-language:
    en:
      list:
      - 425818190040268811
  event:
    admin:
      user:
        ids:
        - 260023416894128130
    text:
    #      channel-command-channel-ids:
    #      - 438667563782897674
    #      - 433998591317508106
    emoji:
      notification-channel-id: 438683201720811520
      command:
        gratuity:
          emojis:
          - id: 438664051954810882
            value: 1
          - id: 438664082917425152
            value: 10
          - id: 438664102307692556
            value: 100
          - id: 438664118589849600
            value: 1000

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:vcoins.db